=begin
#fn

#The open source serverless platform.

OpenAPI spec version: 0.2.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.2.3

=end

require 'spec_helper'
require 'json'

# Unit tests for Fn::CallApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CallApi' do
  before do
    # run before each test
    @instance = Fn::CallApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CallApi' do
    it 'should create an instance of CallApi' do
      expect(@instance).to be_instance_of(Fn::CallApi)
    end
  end

  # unit tests for apps_app_calls_call_get
  # Get call information
  # Get call information
  # @param app app name
  # @param call Call ID.
  # @param [Hash] opts the optional parameters
  # @return [CallWrapper]
  describe 'apps_app_calls_call_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for apps_app_calls_call_log_delete
  # Delete call log entry
  # Delete call log entry
  # @param call Call ID.
  # @param app App name.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'apps_app_calls_call_log_delete test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for apps_app_calls_call_log_get
  # Get call logs
  # Get call logs
  # @param app App Name
  # @param call Call ID.
  # @param [Hash] opts the optional parameters
  # @return [LogWrapper]
  describe 'apps_app_calls_call_log_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for apps_app_calls_get
  # Get app-bound calls.
  # Get app-bound calls can filter to route-bound calls.
  # @param app App name.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :route App route.
  # @return [CallsWrapper]
  describe 'apps_app_calls_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
