=begin
#fn

#The open source serverless platform.

OpenAPI spec version: 0.2.1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.2.3

=end

require 'spec_helper'
require 'json'

# Unit tests for Fn::CallApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CallApi' do
  before do
    # run before each test
    @instance = Fn::CallApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CallApi' do
    it 'should create an instance of CallApi' do
      expect(@instance).to be_instance_of(Fn::CallApi)
    end
  end

  # unit tests for apps_app_calls_call_get
  # Get call information
  # Get call information
  # @param app app name
  # @param call Call ID.
  # @param [Hash] opts the optional parameters
  # @return [CallWrapper]
  describe 'apps_app_calls_call_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for apps_app_calls_call_log_delete
  # Delete call log entry
  # Delete call log entry
  # @param call Call ID.
  # @param app App name.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'apps_app_calls_call_log_delete test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for apps_app_calls_call_log_get
  # Get call logs
  # Get call logs
  # @param app App Name
  # @param call Call ID.
  # @param [Hash] opts the optional parameters
  # @return [LogWrapper]
  describe 'apps_app_calls_call_log_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for apps_app_calls_get
  # Get app-bound calls.
  # Get app-bound calls can filter to route-bound calls, results returned in created_at, descending order (newest first).
  # @param app App name.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :path Route path to match, exact.
  # @option opts [String] :cursor Cursor from previous response.next_cursor to begin results after, if any.
  # @option opts [Integer] :per_page Number of results to return, defaults to 30. Max of 100.
  # @option opts [Integer] :from_time Unix timestamp in seconds, of call.created_at to begin the results at, default 0.
  # @option opts [Integer] :to_time Unix timestamp in seconds, of call.created_at to end the results at, defaults to latest.
  # @return [CallsWrapper]
  describe 'apps_app_calls_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
