=begin
#fn

#The open source serverless platform.

OpenAPI spec version: 0.2.2

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.2.3

=end

require 'spec_helper'
require 'json'

# Unit tests for Fn::LogApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'LogApi' do
  before do
    # run before each test
    @instance = Fn::LogApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of LogApi' do
    it 'should create an instance of LogApi' do
      expect(@instance).to be_instance_of(Fn::LogApi)
    end
  end

  # unit tests for apps_app_calls_call_log_get
  # Get call logs
  # Get call logs
  # @param app App Name
  # @param call Call ID.
  # @param [Hash] opts the optional parameters
  # @return [LogWrapper]
  describe 'apps_app_calls_call_log_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
