=begin
#fn

#The open source serverless platform.

OpenAPI spec version: 0.2.2

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.2.3

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Fn::App
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'App' do
  before do
    # run before each test
    @instance = Fn::App.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of App' do
    it 'should create an instance of App' do
      expect(@instance).to be_instance_of(Fn::App)
    end
  end
  describe 'test attribute "name"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "config"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end

