=begin
#fn

#The open source serverless platform.

OpenAPI spec version: 0.2.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.2.3

=end

# Common files
require 'fn_ruby/api_client'
require 'fn_ruby/api_error'
require 'fn_ruby/version'
require 'fn_ruby/configuration'

# Models
require 'fn_ruby/models/app'
require 'fn_ruby/models/app_wrapper'
require 'fn_ruby/models/apps_wrapper'
require 'fn_ruby/models/call'
require 'fn_ruby/models/call_wrapper'
require 'fn_ruby/models/calls_wrapper'
require 'fn_ruby/models/error'
require 'fn_ruby/models/error_body'
require 'fn_ruby/models/log'
require 'fn_ruby/models/log_wrapper'
require 'fn_ruby/models/route'
require 'fn_ruby/models/route_wrapper'
require 'fn_ruby/models/routes_wrapper'
require 'fn_ruby/models/version'

# APIs
require 'fn_ruby/api/apps_api'
require 'fn_ruby/api/call_api'
require 'fn_ruby/api/log_api'
require 'fn_ruby/api/routes_api'

module Fn
  class << self
    # Customize default settings for the SDK using block.
    #   Fn.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
