=begin
#IronFunctions

#The open source serverless platform.

OpenAPI spec version: 0.1.29

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.2.3

=end

# Common files
require 'fn_ruby/api_client'
require 'fn_ruby/api_error'
require 'fn_ruby/version'
require 'fn_ruby/configuration'

# Models
require 'fn_ruby/models/app'
require 'fn_ruby/models/app_wrapper'
require 'fn_ruby/models/apps_wrapper'
require 'fn_ruby/models/error'
require 'fn_ruby/models/error_body'
require 'fn_ruby/models/new_task'
require 'fn_ruby/models/route'
require 'fn_ruby/models/route_wrapper'
require 'fn_ruby/models/routes_wrapper'
require 'fn_ruby/models/task_wrapper'
require 'fn_ruby/models/version'
require 'fn_ruby/models/task'

# APIs
require 'fn_ruby/api/apps_api'
require 'fn_ruby/api/routes_api'
require 'fn_ruby/api/tasks_api'
require 'fn_ruby/api/version_api'

module OracleFunctions
  class << self
    # Customize default settings for the SDK using block.
    #   OracleFunctions.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
