=begin
#fn

#The open source serverless platform.

OpenAPI spec version: 0.2.2

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.2.3

=end

module Fn
  VERSION = "0.2.2"
end
